routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = App\Models\Product::orderBy('updated_at', 'desc')->paginate(9);

    return view('home', compact('products'));
})->name('home');

Route::resource('products', 'ProductController')->only('index', 'store', 'update', 'destroy');
Route::resource('suppliers', 'SupplierController')->only('index', 'store', 'update', 'destroy');

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $primaryKey = 'id';
    public $incrementing = false;
    protected $fillable = ['id', 'name'];

    public function getTitleAttribute()
    {
        return title_case($this->name);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name', 'price', 'is_active', 'supplier_id', 'image_file'
    ];

    public function getFormatPriceAttribute()
    {
        return 'Rp ' . number_format($this->price, 2, ",", ".");
    }

    public function getStatusLabelAttribute()
    {
        if ($this->is_active) {
            return '<span class="badge badge-md badge-success">' . __('product.active') . '</span>';
        }

        return '<span class="badge badge-md badge-danger">' . __('product.in_active') . '</span>';
    }

    public function getImageUrlAttribute()
    {
        return Storage::url($this->image_file);
    }

    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }
}

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name', 'email', 'city_id', 'birth_year'
    ];

    public function getAgeAttribute()
    {
        return date("Y") - $this->birth_year;
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use App\Models\Product;
use App\Models\Supplier;
use App\Http\Requests\Products\CreateRequest;
use App\Http\Requests\Products\UpdateRequest;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('retrieve.product')->only('index');
    }

    public function index()
    {
        $selectedProduct = request()->selectedProduct;
        $products = Product::orderBy('updated_at', 'desc')->paginate(10);
        $suppliers = Supplier::all()->pluck('name', 'id');

        return view('products.index', compact('selectedProduct', 'products', 'suppliers'));
    }

    public function store(CreateRequest $productCreateForm)
    {
        $productCreateForm->save();

        flash(__('product.created'), 'success');

        return redirect()->route('products.index');
    }

    public function update(UpdateRequest $productUpdateForm, Product $product)
    {
        $productUpdateForm->save();

        flash(__('product.updated'), 'success');

        return redirect()->route('products.index');
    }

    public function destroy(Product $product)
    {
        Storage::delete($product->image_file);
        $product->delete();

        flash(__('product.deleted'), 'success');

        return redirect()->route('products.index');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\City;
use App\Models\Supplier;
use App\Http\Requests\Suppliers\CreateRequest;
use App\Http\Requests\Suppliers\UpdateRequest;

class SupplierController extends Controller
{
    public function __construct()
    {
        $this->middleware('retrieve.supplier')->only('index');
    }

    public function index()
    {
        $selectedSupplier = request()->selectedSupplier;
        $suppliers = Supplier::orderBy('updated_at', 'desc')->paginate(10);

        $cities = City::all()->pluck('title', 'id');
        $years = get_year_range(1945, 2018);

        return view('suppliers.index', compact('selectedSupplier', 'suppliers', 'cities', 'years'));
    }

    public function store(CreateRequest $supplierCreateForm)
    {
        $supplierCreateForm->save();

        flash(__('supplier.created'), 'success');

        return redirect()->route('suppliers.index');
    }

    public function update(UpdateRequest $supplierUpdateForm, Supplier $supplier)
    {
        $supplierUpdateForm->save();

        flash(__('supplier.updated'), 'success');

        return redirect()->route('suppliers.index');
    }

    public function destroy(Supplier $supplier)
    {
        // Delete associate product
        $supplier->products()->get()->each(function($product) {
            $product->delete();
        });

        $supplier->delete();

        flash(__('supplier.deleted'), 'success');

        return redirect()->route('suppliers.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('title') {{ __('app.app_name') }} - {{ __('app.home') }} @endsection

@section('content')
<div class="row">
    <div class="col-md-12 mb-4 mt-5">
        <h2>List Produk</h2>
    </div>
</div>
<div class="row mb-3">
    @foreach ($products as $product)
        <div class="col-md-4 mb-4">
            <div class="card">
                <img class="img-responsive" style="
                    height: 20rem;
                    background-image: url({{ $product->image_url }});
                    background-size: cover;
                    background-repeat: no-repeat;
                    background-position: 50% 50%;">
                <div class="card-body d-flex align-items-center flex-column">
                    <h4 class="card-title font-weight-bold">{{ $product->name }}</h4>
                    <h5 class="card-text font-weight-bold">{{ $product->format_price }}</h5>
                    <p>Supplier: <a href="#">{{ $product->supplier->name }}</a></p>
                </div>
            </div>
        </div>
    @endforeach
</div>
<div class="row d-flex justify-content-center">
    {{ $products->links('layouts.partials.pagination') }}
</div>
@endsection

@push('head')
<style>
</style>
@endpush()

@push('end')
<script>

</script>
@endpush

resources/views/layouts/_footer.blade.php
<footer class="container">
    <p class="float-right">
        <a href="#">Back to top</a>
    </p>
    <p>&copy; 2019 {{ __('app.app_name') }} &middot;
        <a href="#">Privacy</a> &middot;
        <a href="#">Terms</a>
    </p>
  </footer>

resources/views/layouts/_header.blade.php
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{{ route('home') }}"><img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg"
                alt="Logo" width="30" height="30">
        </a>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">{{ __('app.home') }}</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('suppliers.index') }}">{{ __('app.supplier') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('products.index') }}">{{ __('app.product') }}</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @stack('head')
</head>

<body>

    @stack('begin')

    <header>
        @include('layouts._header')
    </header>

    <main role="main">
        <div class="container mt-5">
            @yield('content')
        </div>
        @include('layouts._footer')
    </main>

    <script src="{{ asset('js/app.js') }}"></script>
    @include('layouts.partials.notify')
    @stack('end')

</body>

</html>

resources/views/layouts/partials/notify.blade.php
@if(Session::has('flash_notification.message'))
@php
    $level = Session::get('flash_notification.level');
    if ($level == 'info') {
        $level = 'information';
    }
@endphp
<script src="{{ asset('js/plugins/noty.js') }}"></script>
<script>
    noty({
        type: '{{ $level }}',
        layout: 'topCenter',
        text: '{{ Session::get('flash_notification.message') }}',
        timeout: 3000
    });
</script>
@endif

resources/views/layouts/partials/pagination.blade.php
@if ($paginator->hasPages())
  <ul class="pagination pagination-md">

    {{-- Previous Page Link --}}
    @if ($paginator->onFirstPage())
      <li class="page-item disabled"><span class="page-link nohover">{{ __('app.previous') }}</span></li>
    @else
      <li class="page-item"><a class="page-link" href="{{ $paginator->previousPageUrl() }}">{{ __('app.previous') }}</a></li>
    @endif

    {{-- Pagination Elements --}}
    @foreach ($elements as $element)

      {{-- Array Of Links --}}
      @if (is_array($element))
        @foreach ($element as $page => $url)
          @if ($page == $paginator->currentPage())
            <li class="page-item active"><span class="page-link" >{{ $page }}</span></li>
          @elseif(
            (
              $page === $paginator->currentPage() + 1
              || $page === $paginator->currentPage() + 2
              || $page === $paginator->currentPage() - 1
              || $page === $paginator->currentPage() - 2
            )
              || $page === $paginator->lastPage()
              || $page === 1
          )
            <li class="page-item"><a class="page-link" href="{{ $url }}">{{ $page }}</a></li>
          @elseif(
            $page === $paginator->lastPage()-1
            || $page === 1+1
          )
            <li class="page-item"><span class="page-link" >...</span></li>
          @endif
        @endforeach
      @endif
    @endforeach

    {{-- Next Page Link --}}
    @if ($paginator->hasMorePages())
      <li class="page-item"><a class="page-link" href="{{ $paginator->nextPageUrl() }}">{{ __('app.next') }}</a></li>
    @else
      <li class="page-item disabled"><span class="page-link nohover">{{ __('app.next') }}</span></li>
    @endif
  </ul>
@endif

resources/views/products/_delete_form.blade.php
<div class="modal" id="productModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('product.delete_product') }}</h5>
                    {{ link_to_route('products.index', '&times;', [], ['class' => 'close']) }}
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ __('app.name') }}</label>
                            <p>{{ $selectedProduct->name }}</p>
                        </div>
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ __('app.supplier') }}</label>
                            <p>{{ $selectedProduct->supplier->name }}</p>
                        </div>
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ __('app.price') }}</label>
                            <p>{{ $selectedProduct->format_price }}</p>
                        </div>
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ __('app.status') }}</label>
                            <p>{!! $selectedProduct->status_label !!}</p>
                        </div>
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ __('app.image') }}</label>
                            <img class="img-thumbnail" src="{{ $selectedProduct->image_url }}">
                        </div>
                    </div>
                </div>
                <hr style="margin:0">
                <div class="modal-body">{{ __('product.delete_confirm') }}</div>
                <div class="modal-footer">
                    {!! FormField::delete(
                    ['route' => ['products.destroy', $selectedProduct], 'class' => ''],
                    __('product.delete_confirm_btn'),
                    ['class'=>'btn btn-danger'],
                    []
                    ) !!}
                    {{ link_to_route('products.index', __('product.cancel'), [], ['class' => 'btn btn-secondary']) }}
                </div>
            </div>
        </div>
    </div>

resources/views/products/_store_form.blade.php
<div class="modal" id="productModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('product.add_product') }}</h5>
                    {{ link_to_route('products.index', '&times;', [], ['class' => 'close']) }}
                </div>
                {!! Form::open(['route' => 'products.store', 'files' => true]) !!}
                <div class="modal-body">
                    {!! FormField::text('name', [
                        'required' => true,
                        'label' => __('product.name'),
                        'placeholder' => __('product.name_placeholder')
                    ]) !!}
                    {!! FormField::select('supplier_id', $suppliers, [
                        'required' => true,
                        'label' => __('product.supplier_label'),
                        'placeholder' => __('product.supplier_placeholder'),
                        'class' => 'supplier_id-select2'
                    ]) !!}
                    <div class="form-group required ">
                        <label for="price" class="control-label">{{ __('product.price_label') }}</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Rp</div>
                            </div>
                            <input
                                class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}"
                                placeholder="{{ __('product.price_placeholder') }}"
                                name="price" type="number" id="number"
                                value="{{ request()->old('price') }}"
                            />
                        </div>
                        @if ($errors->has('price'))
                            <p class="text-danger">{{ $errors->first('price') }}</p>
                        @endif
                    </div>
                    <div class="form-group mt-4">
                        <input
                            name="is_active"
                            type="checkbox"
                            data-toggle="toggle"
                            data-on="{{__('product.active')}}"
                            data-off="{{__('product.in_active')}}"
                            data-onstyle="success"
                            data-offstyle="danger"
                            {{ request()->old('is_active') ? 'checked' : '' }}
                        />
                    </div>
                    {!! FormField::file('image') !!}
                </div>
                <div class="modal-footer">
                    {!! Form::submit(__('product.save'), ['class' => 'btn btn-primary']) !!}
                    {{ link_to_route('products.index', __('product.cancel'), [], ['class' => 'btn btn-secondary']) }}
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>

resources/views/products/_update_form.blade.php
<div class="modal" id="productModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('product.edit_product') }}</h5>
                    {{ link_to_route('products.index', '&times;', [], ['class' => 'close']) }}
                </div>
                {!! Form::model($selectedProduct, ['route' => ['products.update', $selectedProduct], 'method' => 'patch', 'files' => true]) !!}
                <div class="modal-body">
                    {!! FormField::text('name', [
                        'required' => true,
                        'label' => __('product.name'),
                        'placeholder' => __('product.name_placeholder')
                    ]) !!}
                    {!! FormField::select('supplier_id', $suppliers, [
                        'required' => true,
                        'label' => __('product.supplier_label'),
                        'placeholder' => __('product.supplier_placeholder'),
                        'class' => 'supplier_id-select2'
                    ]) !!}
                    <div class="form-group required ">
                        <label for="price" class="control-label">{{ __('product.price_label') }}</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">Rp</div>
                            </div>
                            <input
                                class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}"
                                placeholder="{{ __('product.price_placeholder') }}"
                                name="price" type="number" id="number"
                                value="{{ $selectedProduct->price }}"
                            />
                        </div>
                        @if ($errors->has('price'))
                            <p class="text-danger">{{ $errors->first('price') }}</p>
                        @endif
                    </div>
                    <div class="form-group mt-4">
                        <input
                            name="is_active"
                            type="checkbox"
                            data-toggle="toggle"
                            data-on="{{__('product.active')}}"
                            data-off="{{__('product.in_active')}}"
                            data-onstyle="success"
                            data-offstyle="danger"
                            {{ $selectedProduct->is_active ? 'checked' : '' }}
                        />
                    </div>
                    {!! FormField::file('image') !!}
                    <div class="row">
                        <div class="col-md-6">
                            <img class="img-thumbnail" src="{{ $selectedProduct->image_url }}">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {!! Form::submit(__('product.edit'), ['class' => 'btn btn-primary']) !!}
                    {{ link_to_route('products.index', __('product.cancel'), [], ['class' => 'btn btn-secondary']) }}
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>

resources/views/products/forms.blade.php
@if (request('action') == 'create')
    @include('products._store_form')
@endif

@if (request('action') == 'edit' && $selectedProduct)
    @include('products._update_form')
@endif

@if (request('action') == 'delete' && $selectedProduct)
    @include('products._delete_form')
@endif

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title') {{ __('app.app_name') }} - {{ __('product.title') }} @endsection

@section('content')
<div class="row">
    <div class="col-lg-12 mb-4 mt-5">
        <h2>{{ __('product.title_h2') }}</h2>
    </div>
</div>
<div class="row mb-3">
    <div class="col-lg-12">
        {{ link_to_route(
            'products.index',
            __('product.add_product'),
            ['action' => 'create'],
            ['class' => 'btn btn-success float-right']
        ) }}
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">{{ __('app.name') }}</th>
                    <th scope="col">{{ __('app.supplier') }}</th>
                    <th scope="col">{{ __('app.price') }}</th>
                    <th scope="col">{{ __('app.status') }}</th>
                    <th scope="col">{{ __('app.action') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                    <tr>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->supplier->name }}</td>
                        <td>{{ $product->format_price }}</td>
                        <td>{!! $product->status_label !!}</td>
                        <td>
                            {{ link_to_route(
                                'products.index',
                                __('app.edit'),
                                ['action' => 'edit', 'id' => $product->id],
                                [
                                    'id' => 'edit-product-'.$product->id,
                                    'class' => 'btn btn-primary',
                                ]
                            ) }}
                            {!! link_to_route(
                                'products.index',
                                __('app.delete'),
                                ['action' => 'delete', 'id' => $product->id],
                                ['id' => 'del-product-'.$product->id, 'class' => 'btn btn-danger']
                            ) !!}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div class="d-flex justify-content-center">
            {{ $products->links('layouts.partials.pagination') }}
        </div>
    </div>
    <div class="col-md-4">
        @if(Request::has('action'))
            @include('products.forms')
        @endif
    </div>
</div>
<hr class="featurette-divider">
@endsection

@push('head')
    {{ Html::style(url('css/plugins/bootstrap4-toggle.min.css')) }}
    {{ Html::style(url('css/plugins/select2.min.css')) }}
@endpush()

@push('end')
    {{ Html::script(url('js/plugins/bootstrap4-toggle.min.js')) }}
    {{ Html::script(url('js/plugins/select2.min.js')) }}
<script>
(function () {
    $('#productModal').modal({
        show: true,
        backdrop: 'static',
    });
    $('.supplier_id-select2').select2();
})();
</script>
@endpush

resources/views/suppliers/_delete_form.blade.php
<div class="modal" id="supplierModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ __('supplier.delete_supplier') }}</h5>
                {{ link_to_route('suppliers.index', '&times;', [], ['class' => 'close']) }}
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <label class="font-weight-bold">{{ __('supplier.name') }}</label>
                        <p>{!! $selectedSupplier->name !!}</p>
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">{{ __('supplier.email') }}</label>
                        <p>{{ $selectedSupplier->email }}</p>
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">{{ __('supplier.city_label') }}</label>
                        <p>{{ $selectedSupplier->city->title }}</p>
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">{{ __('app.age') }}</label>
                        <p>{{ $selectedSupplier->age }} tahun</p>
                    </div>
                </div>
            </div>
            <hr style="margin:0">
            <div class="modal-body">{{ __('supplier.delete_confirm') }}</div>
            <div class="modal-footer">
                {!! FormField::delete(
                ['route' => ['suppliers.destroy', $selectedSupplier], 'class' => ''],
                __('supplier.delete_confirm_btn'),
                ['class'=>'btn btn-danger'],
                []
                ) !!}
                {{ link_to_route('suppliers.index', __('supplier.cancel'), [], ['class' => 'btn btn-secondary']) }}
            </div>
        </div>
    </div>
</div>

resources/views/suppliers/_store_form.blade.php
<div class="modal" id="supplierModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ __('supplier.add_supplier') }}</h5>
                {{ link_to_route('suppliers.index', '&times;', [], ['class' => 'close']) }}
            </div>
            {!! Form::open(['route' => 'suppliers.store']) !!}
            <div class="modal-body">
                {!! FormField::text('name', [
                'required' => true,
                'label' => __('supplier.name'),
                'placeholder' => __('supplier.name_placeholder')
                ]) !!}
                {!! FormField::email('email', [
                'required' => true,
                'label' => __('supplier.email'),
                'placeholder' => __('supplier.email_placeholder')
                ]) !!}
                {!! FormField::select('city_id', $cities, [
                'required' => true,
                'label' => __('supplier.city_label'),
                'placeholder' => __('supplier.city_placeholder'),
                'class' => 'city_id-select2'
                ]) !!}
                {!! FormField::select('birth_year', $years, [
                'required' => true,
                'label' => __('supplier.birth_year_label'),
                'placeholder' => __('supplier.birth_year_placeholder'),
                'class' => 'birth_year-select2'
                ]) !!}
            </div>
            <div class="modal-footer">
                {!! Form::submit(__('supplier.save'), ['class' => 'btn btn-primary']) !!}
                {{ link_to_route('suppliers.index', __('supplier.cancel'), [], ['class' => 'btn btn-secondary']) }}
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>

resources/views/suppliers/_update_form.blade.php
<div class="modal" id="supplierModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ __('supplier.edit_supplier') }}</h5>
                {{ link_to_route('suppliers.index', '&times;', [], ['class' => 'close']) }}
            </div>
            {!! Form::model($selectedSupplier, ['route' => ['suppliers.update', $selectedSupplier], 'method' =>
            'patch']) !!}
            <div class="modal-body">
                {!! FormField::text('name', [
                'required' => true,
                'label' => __('supplier.name'),
                'placeholder' => __('supplier.name_placeholder')
                ]) !!}
                {!! FormField::email('email', [
                'label' => __('supplier.email'),
                'placeholder' => __('supplier.email_placeholder'),
                'disabled' => 'disabled',
                ]) !!}
                {!! FormField::select('city_id', $cities, [
                'required' => true,
                'label' => __('supplier.city_label'),
                'placeholder' => __('supplier.city_placeholder'),
                'class' => 'city_id-select2'
                ]) !!}
                {!! FormField::select('birth_year', $years, [
                'required' => true,
                'label' => __('supplier.birth_year_label'),
                'placeholder' => __('supplier.birth_year_placeholder'),
                'class' => 'birth_year-select2'
                ]) !!}
            </div>
            <div class="modal-footer">
                {!! Form::submit(__('supplier.edit'), ['class' => 'btn btn-primary']) !!}
                {{ link_to_route('suppliers.index', __('supplier.cancel'), [], ['class' => 'btn btn-secondary']) }}
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>

resources/views/suppliers/forms.blade.php
@if (request('action') == 'create')
    @include('suppliers._store_form')
@endif

@if (request('action') == 'edit' && $selectedSupplier)
    @include('suppliers._update_form')
@endif

@if (request('action') == 'delete' && $selectedSupplier)
    @include('suppliers._delete_form')
@endif